"""Turns the Hindi lines under the emblem into vector outlines (src/brand/hindi-paths.ts).

SVG <text> in Devanagari depends on the viewer's fonts and breaks apart in some browsers
(matras and conjuncts come out as separate letters with dotted circles). Outlines look the
same everywhere. Run again after changing a brand's Hindi line:
  python3 -m pip install uharfbuzz fonttools brotli
  python3 scripts/hindi-paths.py path/to/mukta-devanagari-700-normal.woff2
(the font is in the @fontsource/mukta npm package)."""
import io, json, sys
import uharfbuzz as hb
from fontTools.ttLib import TTFont
from fontTools.pens.svgPathPen import SVGPathPen
from fontTools.pens.transformPen import TransformPen

LINES = ["अतुल्य उत्तर प्रदेश", "यूपी की प्रामाणिक पहचान"]
SIZE = 17  # font-size in the emblem's 240-wide viewBox

data = open(sys.argv[1], "rb").read()
tt = TTFont(io.BytesIO(data))
upem = tt["head"].unitsPerEm
glyphs = tt.getGlyphSet()
order = tt.getGlyphOrder()
buf_tt = io.BytesIO(); tt.flavor = None; tt.save(buf_tt)
font = hb.Font(hb.Face(hb.Blob(buf_tt.getvalue())))

out = {}
for line in LINES:
    buf = hb.Buffer(); buf.add_str(line); buf.guess_segment_properties()
    hb.shape(font, buf, {})
    s = SIZE / upem
    pen = SVGPathPen(glyphs, ntos=lambda v: f"{v:.2f}".rstrip("0").rstrip("."))
    x = 0
    for info, pos in zip(buf.glyph_infos, buf.glyph_positions):
        # flip y (font units point up, SVG points down) and scale to the emblem size
        glyphs[order[info.codepoint]].draw(TransformPen(pen, (s, 0, 0, -s, (x + pos.x_offset) * s, -pos.y_offset * s)))
        x += pos.x_advance
    out[line] = {"d": pen.getCommands(), "width": round(x * s, 2)}

with open("src/brand/hindi-paths.ts", "w") as f:
    f.write("// Generated by scripts/hindi-paths.py from Mukta Bold. Do not edit by hand.\n")
    f.write("// Each line is drawn with its baseline at y=0, starting at x=0, at font-size 17.\n")
    f.write("export const HINDI_PATHS: Record<string, { d: string; width: number }> = " + json.dumps(out, ensure_ascii=False, indent=2) + ";\n")
print({k: v["width"] for k, v in out.items()})
